{{- range $language, $config := .Values.languages }}
{{- if $config.useChroma }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-chroma-{{ $language }}-{{ $.Values.backend.checkpointRelease | replace "/" "-" | replace "." "-" | lower }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}-chroma-{{ $language }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: chroma-{{ $language }}
    istaroth.me/checkpoint-release: {{ $.Values.backend.checkpointRelease | replace "/" "-" | quote }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.chroma.service.type }}
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ $.Release.Name }}-chroma-{{ $language }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    istaroth.me/checkpoint-release: {{ $.Values.backend.checkpointRelease | replace "/" "-" | quote }}
{{- end }}
{{- end }}
