apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  {{- /* Generate ISTAROTH_DOCUMENT_STORE_SET from languages config */ -}}
  {{- if .Values.languages }}
  {{- $stores := list }}
  {{- range $lang, $config := .Values.languages }}
    {{- $path := printf "/data/checkpoints/%s/%s" ($.Values.backend.checkpointRelease | replace "/" "-") $lang }}
    {{- $storeEntry := printf "%s:%s" (upper $lang) $path }}
    {{- $stores = append $stores $storeEntry }}
  {{- end }}
  ISTAROTH_DOCUMENT_STORE_SET: {{ join "," $stores | quote }}
  {{- end }}

  {{- /* Generate ISTAROTH_EXTERNAL_CHROMA_SERVERS from languages config */ -}}
  {{- $chromaServers := list }}
  {{- range $lang, $config := .Values.languages }}
    {{- if $config.useChroma }}
      {{- $serverHost := printf "%s-chroma-%s-%s" $.Release.Name $lang ($.Values.backend.checkpointRelease | replace "/" "-" | replace "." "-" | lower) }}
      {{- $serverEntry := printf "%s:%s:8000" (upper $lang) $serverHost }}
      {{- $chromaServers = append $chromaServers $serverEntry }}
    {{- end }}
  {{- end }}
  {{- if $chromaServers }}
  ISTAROTH_EXTERNAL_CHROMA_SERVERS: {{ join "," $chromaServers | quote }}
  {{- end }}
