{{- if .Values.embedding.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-embedding
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-embedding
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: embedding
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.embedding.service.type }}
  ports:
  - port: {{ .Values.embedding.service.port }}
    targetPort: {{ .Values.embedding.service.port }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-embedding
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
